Future proof NMake.v and ZMake.v
coq/bignums pull request #58
Opened 2021-04-09 14:39 UTC by mrhaandi

This PR makes NMake.v and ZMake.v work with https://github.com/coq/coq/pull/14086 in a backwards compatible manner.

2021-04-10 17:28 UTC, Zimmi48 commented
I'm not able to review this, but if knowledgeable people do it, you may ping me to merge it.

2021-04-10 17:30 UTC, mrhaandi commented
Any suggestions on who to ask to review?

2021-04-10 17:32 UTC, Zimmi48 commented
In the main PR, @fajb proposed @thery. Otherwise, I guess any of the reviewers of the main PR would do.

2021-04-10 18:11 UTC, thery requested changes
Look good to me.

2021-04-10 18:11 UTC, thery commented on BigN/NMake.v
> +  if eqb y zero then (match (1 mod 0) with | 0 => zero | _ => x end) else
As for``Coqprime`, try to do such that `Print modulo` shows reasonable code.

2021-04-10 18:11 UTC, thery commented on BigZ/ZMake.v
> +      if NN.eqb NN.zero ny
Sorry stupid question I don't understand why in the case of `N1`the change is static here it is dynamic. Is this backward compatible?

2021-04-10 18:22 UTC, mrhaandi commented on BigZ/ZMake.v
> +      if NN.eqb NN.zero ny
This `div_eucl` is quite different from the others with the benefit that the new algorithm in fact also captures the behavior of the old one (which has advantages for a uniform proof).
I tested it before and after https://github.com/coq/coq/pull/14086, but I encourage you to do so as well to be sure.
Specifically, the added `NN.eqb NN.zero ny` in previous corner case `x mod 0 = 0` would not be reached.

2021-04-10 18:22 UTC, mrhaandi commented on BigN/NMake.v
> +  if eqb y zero then (match (1 mod 0) with | 0 => zero | _ => x end) else
will fix

2021-04-11 02:18 UTC, thery commented
I ve just realized that `bignums` uses `Int63` for its base digits. The `Int63` do have to comply with the new modulo. On my machine
they are not:
```
Require Import Int63.
Open Scope int63_scope.
Compute 123 mod 0.
     = 0
     : int
```

There is an axiom `Coq.Numbers.Cyclic.Int63.Int63.mod_spec`. Do you plan to do an overlay for the Int31 and Int63 implementations too. Is this not tricky?

2021-04-11 16:26 UTC, mrhaandi commented
Now this PR considers previous review comments. It compiles with the most recent int63 changes in https://github.com/coq/coq/pull/14086.
The PR also works without https://github.com/coq/coq/pull/14086.

2021-04-12 13:26 UTC, thery commented
I'm still puzzled. I wonder if this does not mean we could (should?) drop the condition 
` 0 < [|b|]` in `spec_modulo_gt` and `spec_modulo` in `Numbers/Cyclic/Abstract/CyclicAxion`.

2021-04-12 13:34 UTC, mrhaandi commented
> I'm still puzzled. I wonder if this does not mean we could (should?) drop the condition
> ` 0 < [|b|]` in `spec_modulo_gt` and `spec_modulo` in `Numbers/Cyclic/Abstract/CyclicAxion`.

This is likely. I observed that abstract specifications such as used in `Numbers/NatInt/NZDiv` can be simplified/strengthened. See also `EuclidSpec` in the `math_classes` project.

2021-04-12 13:36 UTC, mrhaandi commented
@thery The PR says "Changes requested". Does it still apply?

2021-04-12 13:37 UTC, thery commented
I guess as division by zero has no sense I guess it is fair enough to do the same for modulo

2021-04-12 13:42 UTC, thery approved these changes

2021-04-12 13:44 UTC, thery commented
I've approved the change
I'm still puzzled by the interest of this change for bignums but if it helps other part of Coq this is ok with one.

2021-04-12 13:55 UTC, merged